// Generated by scripts/build-course-catalog.js. Do not edit by hand.
const CATALOG = [
  {
    "id": "BUS",
    "label": "Business",
    "courses": [
      {
        "code": "BUS13-2",
        "name": "Designing Operations from Scratch",
        "folder": "BUS13-2 - Designing Operations from Scratch",
        "chapters": [
          {
            "id": "00-preface",
            "title": "Preface"
          },
          {
            "id": "01-operations-as-a-function",
            "title": "Operations as a function"
          },
          {
            "id": "02-systems-thinking-as-an-operational-lens",
            "title": "Systems thinking as an operational lens"
          },
          {
            "id": "03-constraints-and-the-theory-of-constraints",
            "title": "Constraints and the Theory of Constraints"
          },
          {
            "id": "04-throughput-utilization-and-the-cost-of-being-busy",
            "title": "Throughput, utilization, and the cost of being busy"
          },
          {
            "id": "05-queues-flow-and-little-s-law",
            "title": "Queues, flow, and Little's Law"
          },
          {
            "id": "06-designing-a-process-from-scratch",
            "title": "Designing a process from scratch"
          },
          {
            "id": "07-service-design",
            "title": "Service design"
          },
          {
            "id": "08-make-vs-buy",
            "title": "Make vs. buy"
          },
          {
            "id": "09-unit-economics-as-operational-constraints",
            "title": "Unit economics as operational constraints"
          },
          {
            "id": "10-operational-mvp-and-failure-mode-analysis",
            "title": "Operational MVP and failure-mode analysis"
          },
          {
            "id": "11-primary-sources-and-further-reading",
            "title": "Primary sources and further reading"
          }
        ]
      },
      {
        "code": "BUS23-1",
        "name": "Sales, Negotiation & Client Relations",
        "folder": "BUS23-1 - Sales, Negotiation & Client Relations",
        "chapters": [
          {
            "id": "00-preface",
            "title": "Preface"
          },
          {
            "id": "01-the-harvard-negotiation-framework",
            "title": "The Harvard Negotiation Framework"
          },
          {
            "id": "02-the-psychology-of-influence",
            "title": "The Psychology of Influence"
          },
          {
            "id": "03-the-structured-sales-cycle",
            "title": "The Structured Sales Cycle"
          },
          {
            "id": "04-objection-handling-and-closing",
            "title": "Objection Handling and Closing"
          },
          {
            "id": "05-sales-pipeline-economics-and-funnel-hygiene",
            "title": "Sales-Pipeline Economics and Funnel Hygiene"
          },
          {
            "id": "06-value-based-pricing-conversations",
            "title": "Value-Based Pricing Conversations"
          },
          {
            "id": "07-client-relationship-management-over-time",
            "title": "Client Relationship Management over Time"
          },
          {
            "id": "08-multi-party-and-team-negotiation-advanced-tactics",
            "title": "Multi-Party and Team Negotiation; Advanced Tactics"
          },
          {
            "id": "09-sales-ethics-persuasion-vs-manipulation",
            "title": "Sales Ethics: Persuasion vs Manipulation"
          },
          {
            "id": "10-primary-sources-and-further-reading",
            "title": "Primary sources and further reading"
          }
        ]
      },
      {
        "code": "BUS33-3",
        "name": "Corporate Finance",
        "folder": "BUS33-3 - Corporate Finance",
        "chapters": [
          {
            "id": "00-preface",
            "title": "Preface"
          },
          {
            "id": "01-time-value-of-money",
            "title": "Time value of money"
          },
          {
            "id": "02-net-present-value-and-the-investment-decision",
            "title": "Net Present Value and the investment decision"
          },
          {
            "id": "03-internal-rate-of-return",
            "title": "Internal Rate of Return"
          },
          {
            "id": "04-cost-of-equity-via-capm",
            "title": "Cost of equity via CAPM"
          },
          {
            "id": "05-cost-of-debt",
            "title": "Cost of debt"
          },
          {
            "id": "06-weighted-average-cost-of-capital",
            "title": "Weighted Average Cost of Capital"
          },
          {
            "id": "07-capital-structure",
            "title": "Capital structure"
          },
          {
            "id": "08-payout-policy",
            "title": "Payout policy"
          },
          {
            "id": "09-value-creation-metrics",
            "title": "Value-creation metrics"
          },
          {
            "id": "10-the-integrated-investment-case",
            "title": "The integrated investment case"
          },
          {
            "id": "11-further-reading",
            "title": "Further reading"
          }
        ]
      },
      {
        "code": "BUS33-4",
        "name": "Labour Economics & Inequalities",
        "folder": "BUS33-4 - Labour Economics & Inequalities",
        "chapters": [
          {
            "id": "00-preface",
            "title": "Preface"
          },
          {
            "id": "01-labour-supply-the-work-leisure-choice",
            "title": "Labour supply: the work–leisure choice"
          },
          {
            "id": "02-labour-demand-the-marginal-product-condition",
            "title": "Labour demand: the marginal-product condition"
          },
          {
            "id": "03-human-capital",
            "title": "Human capital"
          },
          {
            "id": "04-wage-structure-differentials-discrimination-decomposition",
            "title": "Wage structure: differentials, discrimination, decomposition"
          },
          {
            "id": "05-unemployment-frictions-matching-and-the-natural-rate",
            "title": "Unemployment: frictions, matching, and the natural rate"
          },
          {
            "id": "06-institutions-and-the-minimum-wage-debate",
            "title": "Institutions and the minimum-wage debate"
          },
          {
            "id": "07-inequality-measurement",
            "title": "Inequality measurement"
          },
          {
            "id": "08-wealth-inequality-and-its-dynamics",
            "title": "Wealth inequality and its dynamics"
          },
          {
            "id": "09-causal-inference-for-labour-market-policy",
            "title": "Causal inference for labour-market policy"
          },
          {
            "id": "10-automation-and-labour-market-polarisation",
            "title": "Automation and labour-market polarisation"
          },
          {
            "id": "11-primary-sources",
            "title": "Primary sources"
          },
          {
            "id": "12-further-reading",
            "title": "Further reading"
          }
        ]
      }
    ]
  },
  {
    "id": "DAT",
    "label": "Data",
    "courses": [
      {
        "code": "DAT12-1",
        "name": "Introduction to Data with Spreadsheet",
        "folder": "DAT12-1 - Introduction to Data with Spreadsheet",
        "chapters": [
          {
            "id": "00-preface",
            "title": "Preface"
          },
          {
            "id": "01-the-spreadsheet-environment",
            "title": "The Spreadsheet Environment"
          },
          {
            "id": "02-core-functions",
            "title": "Core Functions"
          },
          {
            "id": "03-looking-up-related-values",
            "title": "Looking Up Related Values"
          },
          {
            "id": "04-sorting-and-filtering",
            "title": "Sorting and Filtering"
          },
          {
            "id": "05-data-quality-at-the-spreadsheet-level",
            "title": "Data Quality at the Spreadsheet Level"
          },
          {
            "id": "06-pivot-tables",
            "title": "Pivot Tables"
          },
          {
            "id": "07-visualization",
            "title": "Visualization"
          },
          {
            "id": "08-from-business-question-to-spreadsheet-answer",
            "title": "From Business Question to Spreadsheet Answer"
          },
          {
            "id": "09-documentation-and-reproducibility",
            "title": "Documentation and Reproducibility"
          }
        ]
      },
      {
        "code": "DAT12-2",
        "name": "Programming in Python",
        "folder": "DAT12-2 - Programming in Python",
        "chapters": [
          {
            "id": "00-preface",
            "title": "Preface"
          },
          {
            "id": "01-the-development-environment",
            "title": "The development environment"
          },
          {
            "id": "02-core-data-types",
            "title": "Core data types"
          },
          {
            "id": "03-control-flow",
            "title": "Control flow"
          },
          {
            "id": "04-functions",
            "title": "Functions"
          },
          {
            "id": "05-file-input-and-output",
            "title": "File input and output"
          },
          {
            "id": "06-debugging",
            "title": "Debugging"
          },
          {
            "id": "07-third-party-libraries",
            "title": "Third-party libraries"
          },
          {
            "id": "08-virtual-environments-revisited",
            "title": "Virtual environments, revisited"
          },
          {
            "id": "09-data-processing-from-csv-to-csv",
            "title": "Data processing: from CSV to CSV"
          },
          {
            "id": "10-objects-using-what-libraries-give-you",
            "title": "Objects: using what libraries give you"
          },
          {
            "id": "11-a-first-encounter-with-apis",
            "title": "A first encounter with APIs"
          },
          {
            "id": "12-glossary",
            "title": "Glossary"
          }
        ]
      },
      {
        "code": "DAT12-3",
        "name": "Pandas I",
        "folder": "DAT12-3 - Pandas I",
        "chapters": [
          {
            "id": "00-preface",
            "title": "Preface"
          },
          {
            "id": "01-dataframes-and-series",
            "title": "DataFrames and Series"
          },
          {
            "id": "02-selection-and-filtering",
            "title": "Selection and Filtering"
          },
          {
            "id": "03-missing-values",
            "title": "Missing Values"
          },
          {
            "id": "04-groupby-and-aggregation",
            "title": "Groupby and Aggregation"
          },
          {
            "id": "05-merging-and-concatenating",
            "title": "Merging and Concatenating"
          },
          {
            "id": "06-reshaping-wide-and-long",
            "title": "Reshaping: Wide and Long"
          },
          {
            "id": "07-applying-functions",
            "title": "Applying Functions"
          },
          {
            "id": "08-the-end-to-end-pipeline",
            "title": "The End-to-End Pipeline"
          },
          {
            "id": "09-visualization",
            "title": "Visualization"
          },
          {
            "id": "10-descriptive-reporting",
            "title": "Descriptive Reporting"
          }
        ]
      },
      {
        "code": "DAT22-5",
        "name": "SQL & Data Querying",
        "folder": "DAT22-5 - SQL & Data Querying",
        "chapters": [
          {
            "id": "00-preface",
            "title": "Preface"
          },
          {
            "id": "01-the-relational-model-and-your-first-select",
            "title": "The relational model and your first SELECT"
          },
          {
            "id": "02-aggregate-functions",
            "title": "Aggregate functions"
          },
          {
            "id": "03-joins",
            "title": "Joins"
          },
          {
            "id": "04-subqueries-and-ctes",
            "title": "Subqueries and CTEs"
          },
          {
            "id": "05-creating-and-manipulating-tables",
            "title": "Creating and manipulating tables"
          },
          {
            "id": "06-database-types-relational-warehouse-flat-file",
            "title": "Database types: relational, warehouse, flat file"
          },
          {
            "id": "07-connecting-to-sqlite-from-python",
            "title": "Connecting to SQLite from Python"
          },
          {
            "id": "08-data-quality-at-the-query-level",
            "title": "Data quality at the query level"
          },
          {
            "id": "09-from-business-question-to-sql",
            "title": "From business question to SQL"
          },
          {
            "id": "10-indexing-and-query-performance",
            "title": "Indexing and query performance"
          }
        ]
      },
      {
        "code": "DAT32-1",
        "name": "Intro to Machine Learning",
        "folder": "DAT32-1 - Intro to Machine Learning",
        "chapters": [
          {
            "id": "00-preface",
            "title": "Preface"
          },
          {
            "id": "01-what-machine-learning-is-taxonomy-and-workflow",
            "title": "What machine learning is: taxonomy and workflow"
          },
          {
            "id": "02-core-vocabulary-built-by-hand",
            "title": "Core vocabulary, built by hand"
          },
          {
            "id": "03-simple-linear-regression-from-first-principles",
            "title": "Simple linear regression from first principles"
          },
          {
            "id": "04-baselines-and-evaluation-metrics",
            "title": "Baselines and evaluation metrics"
          },
          {
            "id": "05-gradient-descent",
            "title": "Gradient descent"
          },
          {
            "id": "06-underfitting-and-overfitting",
            "title": "Underfitting and overfitting"
          },
          {
            "id": "07-regularization",
            "title": "Regularization"
          },
          {
            "id": "08-cross-validation",
            "title": "Cross-validation"
          },
          {
            "id": "09-hyperparameters",
            "title": "Hyperparameters"
          },
          {
            "id": "10-from-simple-to-multiple-regression",
            "title": "From simple to multiple regression"
          },
          {
            "id": "11-reproducible-workflows-scikit-learn-pipelines",
            "title": "Reproducible workflows: scikit-learn pipelines"
          }
        ]
      },
      {
        "code": "DAT32-91",
        "name": "Prompt Engineering and Git",
        "folder": "DAT32-91 - Prompt Engineering and Git",
        "chapters": [
          {
            "id": "00-preface",
            "title": "Preface"
          },
          {
            "id": "01-why-version-control",
            "title": "Why Version Control"
          },
          {
            "id": "02-git-as-a-daily-reflex",
            "title": "Git as a Daily Reflex"
          },
          {
            "id": "03-branching-merging-and-conflicts",
            "title": "Branching, Merging, and Conflicts"
          },
          {
            "id": "04-pull-requests-and-code-review",
            "title": "Pull Requests and Code Review"
          },
          {
            "id": "05-structuring-an-ai-project-repository",
            "title": "Structuring an AI Project Repository"
          },
          {
            "id": "06-how-a-language-model-generates-text",
            "title": "How a Language Model Generates Text"
          },
          {
            "id": "07-llms-chatbots-and-agents",
            "title": "LLMs, Chatbots, and Agents"
          },
          {
            "id": "08-prompting-as-a-craft",
            "title": "Prompting as a Craft"
          },
          {
            "id": "09-structuring-a-prompt",
            "title": "Structuring a Prompt"
          },
          {
            "id": "10-calling-an-llm-api-from-python",
            "title": "Calling an LLM API from Python"
          },
          {
            "id": "11-how-llms-fail",
            "title": "How LLMs Fail"
          },
          {
            "id": "12-where-to-read-next",
            "title": "Where to Read Next"
          }
        ]
      },
      {
        "code": "DAT32-92",
        "name": "Machine Learning I — Linear and Logistic (Compact)",
        "folder": "DAT32-92 - Machine Learning I — Linear and Logistic (Compact)",
        "chapters": [
          {
            "id": "00-preface",
            "title": "Preface"
          },
          {
            "id": "01-from-regression-to-classification",
            "title": "From regression to classification"
          },
          {
            "id": "02-logistic-regression",
            "title": "Logistic regression"
          },
          {
            "id": "03-the-confusion-matrix-and-the-core-metrics",
            "title": "The confusion matrix and the core metrics"
          },
          {
            "id": "04-the-decision-threshold-and-the-roc-curve",
            "title": "The decision threshold and the ROC curve"
          },
          {
            "id": "05-multi-class-classification",
            "title": "Multi-class classification"
          },
          {
            "id": "06-feature-scaling",
            "title": "Feature scaling"
          },
          {
            "id": "07-feature-engineering-for-linear-models",
            "title": "Feature engineering for linear models"
          },
          {
            "id": "08-regularization-for-logistic-regression",
            "title": "Regularization for logistic regression"
          },
          {
            "id": "09-when-simple-models-win",
            "title": "When simple models win"
          },
          {
            "id": "10-the-end-to-end-classification-pipeline",
            "title": "The end-to-end classification pipeline"
          },
          {
            "id": "11-sources-and-further-reading",
            "title": "Sources and further reading"
          }
        ]
      }
    ]
  },
  {
    "id": "HUM",
    "label": "Humanities",
    "courses": [
      {
        "code": "HUM14-3",
        "name": "Philosophy I — The Examined Life",
        "folder": "HUM14-3 - Philosophy I — The Examined Life",
        "chapters": [
          {
            "id": "00-preface",
            "title": "Preface"
          },
          {
            "id": "01-turning-success-into-a-question",
            "title": "Turning success into a question"
          },
          {
            "id": "02-making-and-supporting-a-claim",
            "title": "Making and supporting a claim"
          },
          {
            "id": "03-objecting-and-following-an-idea-to-aporia",
            "title": "Objecting, and following an idea to aporia"
          },
          {
            "id": "04-conceptualising-defining-and-distinguishing",
            "title": "Conceptualising: defining and distinguishing"
          },
          {
            "id": "05-interpreting",
            "title": "Interpreting"
          },
          {
            "id": "06-five-criteria-for-a-successful-life",
            "title": "Five criteria for a successful life"
          },
          {
            "id": "07-constructing-and-defending-a-thesis-on-success",
            "title": "Constructing and defending a thesis on success"
          }
        ]
      }
    ]
  },
  {
    "id": "MAT",
    "label": "Mathematics",
    "courses": [
      {
        "code": "MAT11-1",
        "name": "Foundations",
        "folder": "MAT11-1 - Foundations",
        "chapters": [
          {
            "id": "00-preface",
            "title": "Preface"
          },
          {
            "id": "01-the-language-of-logic",
            "title": "The Language of Logic"
          },
          {
            "id": "02-sets",
            "title": "Sets"
          },
          {
            "id": "03-counting-combinatorics",
            "title": "Counting: Combinatorics"
          },
          {
            "id": "04-methods-of-proof",
            "title": "Methods of Proof"
          },
          {
            "id": "05-sums-and-products",
            "title": "Sums and Products"
          },
          {
            "id": "06-functions",
            "title": "Functions"
          },
          {
            "id": "07-comparing-infinities",
            "title": "Comparing Infinities"
          },
          {
            "id": "08-sequences",
            "title": "Sequences"
          },
          {
            "id": "09-differentiation",
            "title": "Differentiation"
          },
          {
            "id": "10-integration",
            "title": "Integration"
          },
          {
            "id": "11-notation-reference",
            "title": "Notation reference"
          },
          {
            "id": "12-appendix-derivatives-and-antiderivatives",
            "title": "Appendix: derivatives and antiderivatives"
          }
        ]
      },
      {
        "code": "MAT11-3",
        "name": "Linear Algebra I",
        "folder": "MAT11-3 - Linear Algebra I",
        "chapters": [
          {
            "id": "00-preface",
            "title": "Preface"
          },
          {
            "id": "01-the-space-rn",
            "title": "The space Rn"
          },
          {
            "id": "02-matrix-arithmetic",
            "title": "Matrix arithmetic"
          },
          {
            "id": "03-linear-systems",
            "title": "Linear systems"
          },
          {
            "id": "04-a-matrix-acting-on-a-vector",
            "title": "A matrix acting on a vector"
          },
          {
            "id": "05-invertible-matrices",
            "title": "Invertible matrices"
          },
          {
            "id": "06-vector-spaces",
            "title": "Vector spaces"
          },
          {
            "id": "07-subspaces",
            "title": "Subspaces"
          },
          {
            "id": "08-linear-independence-bases-dimension",
            "title": "Linear independence, bases, dimension"
          },
          {
            "id": "09-grassmann-s-formula",
            "title": "Grassmann's formula"
          },
          {
            "id": "10-linear-maps",
            "title": "Linear maps"
          },
          {
            "id": "11-matrix-representation-and-change-of-basis",
            "title": "Matrix representation and change of basis"
          }
        ]
      },
      {
        "code": "MAT31-1",
        "name": "Linear Algebra III — Euclidean Spaces",
        "folder": "MAT31-1 - Linear Algebra III — Euclidean Spaces",
        "chapters": [
          {
            "id": "00-preface",
            "title": "Preface"
          },
          {
            "id": "01-the-scalar-product",
            "title": "The scalar product"
          },
          {
            "id": "02-norm-cauchy-schwarz-and-angle",
            "title": "Norm, Cauchy–Schwarz, and angle"
          },
          {
            "id": "03-orthogonality-and-orthonormal-bases",
            "title": "Orthogonality and orthonormal bases"
          },
          {
            "id": "04-the-gram-schmidt-process",
            "title": "The Gram–Schmidt process"
          },
          {
            "id": "05-orthogonal-matrices",
            "title": "Orthogonal matrices"
          },
          {
            "id": "06-symmetric-matrices-and-the-spectral-theorem",
            "title": "Symmetric matrices and the spectral theorem"
          },
          {
            "id": "07-quadratic-forms-and-positive-definiteness",
            "title": "Quadratic forms and positive definiteness"
          },
          {
            "id": "08-orthogonal-complement-and-projection",
            "title": "Orthogonal complement and projection"
          },
          {
            "id": "09-best-approximation-distance-and-least-squares",
            "title": "Best approximation, distance, and least squares"
          }
        ]
      },
      {
        "code": "MAT31-6",
        "name": "Math for Data Practice",
        "folder": "MAT31-6 - Math for Data Practice",
        "chapters": [
          {
            "id": "00-preface",
            "title": "Preface"
          },
          {
            "id": "01-covariance-and-correlation",
            "title": "Covariance and correlation"
          },
          {
            "id": "02-the-least-squares-line",
            "title": "The least-squares line"
          },
          {
            "id": "03-decomposing-the-variance-r2",
            "title": "Decomposing the variance: R2"
          },
          {
            "id": "04-residuals-and-the-normality-assumption",
            "title": "Residuals and the normality assumption"
          },
          {
            "id": "05-testing-the-slope",
            "title": "Testing the slope"
          },
          {
            "id": "06-simpson-s-paradox-and-confounding",
            "title": "Simpson's paradox and confounding"
          },
          {
            "id": "07-primary-sources-and-further-reading",
            "title": "Primary sources and further reading"
          }
        ]
      },
      {
        "code": "MAT31-91",
        "name": "Probability & Statistics II — Continuous, Limit Theorems & Confidence Intervals",
        "folder": "MAT31-91 - Probability & Statistics II — Continuous, Limit Theorems & Confidence Intervals",
        "chapters": [
          {
            "id": "00-preface",
            "title": "Preface"
          },
          {
            "id": "01-generalized-integrals",
            "title": "Generalized integrals"
          },
          {
            "id": "02-continuous-random-variables",
            "title": "Continuous random variables"
          },
          {
            "id": "03-classic-continuous-distributions",
            "title": "Classic continuous distributions"
          },
          {
            "id": "04-the-law-of-large-numbers",
            "title": "The Law of Large Numbers"
          },
          {
            "id": "05-the-central-limit-theorem",
            "title": "The Central Limit Theorem"
          },
          {
            "id": "06-monte-carlo-methods",
            "title": "Monte Carlo methods"
          },
          {
            "id": "07-hypothesis-testing",
            "title": "Hypothesis testing"
          },
          {
            "id": "08-confidence-intervals",
            "title": "Confidence intervals"
          },
          {
            "id": "09-further-reading",
            "title": "Further reading"
          }
        ]
      },
      {
        "code": "MAT31-92",
        "name": "Applied Probability and Simulation",
        "folder": "MAT31-92 - Applied Probability and Simulation",
        "chapters": [
          {
            "id": "00-preface",
            "title": "Preface"
          },
          {
            "id": "01-simulating-the-discrete-laws",
            "title": "Simulating the discrete laws"
          },
          {
            "id": "02-simulating-the-continuous-laws",
            "title": "Simulating the continuous laws"
          },
          {
            "id": "03-the-law-of-large-numbers-and-the-central",
            "title": "The Law of Large Numbers and the Central Limit Theorem"
          },
          {
            "id": "04-maximum-likelihood-estimation",
            "title": "Maximum-likelihood estimation"
          },
          {
            "id": "05-checking-an-estimator-by-simulation",
            "title": "Checking an estimator by simulation"
          },
          {
            "id": "06-chi-square-tests",
            "title": "Chi-square tests"
          },
          {
            "id": "07-comparing-a-mean-or-a-proportion",
            "title": "Comparing a mean or a proportion"
          },
          {
            "id": "08-resampling-methods",
            "title": "Resampling methods"
          },
          {
            "id": "09-primary-sources",
            "title": "Primary sources"
          }
        ]
      }
    ]
  }
];
